### ISSUE TITLE
Hackbot should greet new people joining slack

### ISSUE THREAD

**Issue by pcunning** [rogue-hack-lab/hackbot#41]
It would be ideal if new people were greeted with a better message than "Gotcha". Hackbot could PM the new member with some standardised information and introduce the member in #general. It would be kind of cool if hackbot asked the person some questions and reported that in its introduction.

**Comment by joshmerritt** [comment]
I'll tackle adding something more verbose to welcome new members to slack

**Comment by pcunning** [comment]
fixed in #74
